name: Deploy in EC2 instance


on :
  push:
    branches:
      -main

  pull_request:
    branches:
      -main
jobs:
  build: #user defined
  runs-on: ubuntu_latest


  steps:
    -name: Checkout the code base
     uses: actions/checkout@v4
